version: '3.9'
services:
    client:
        container_name: real_estate_deals
        image: custom-node-alpine
        volumes:
            - ./:/var/www/
        networks:
            - homelab
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.real_estate_deals.rule=Host(`real-estate-deals.issamounejjar.live`)'
            - 'traefik.http.routers.real_estate_deals.entrypoints=websecure'
            - 'traefik.http.routers.real_estate_deals.tls.certresolver=letsencrypt'
        restart: unless-stopped

networks:
    homelab:
        external: true
